name: brume_lamp_example
description: "Brume Lamp - On-device yoga and rest teacher"
publish_to: 'none'
version: 1.3.0+1
environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  user_screen:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  config:
    enable-swift-package-manager: false
